
#World Stripper - Settings File
[SETTINGS]
	#Strip Radius: X
	#Range: 0 ~ 256
	stripRadiusX = 32
	#Strip Radius: Z
	#Range: 0 ~ 256
	stripRadiusZ = 32
	#Strip Start: Y
	#Range: -10240 ~ 10240
	stripStartY = 512
	#Strip Stop: Y
	#Range: -10240 ~ 10240
	stripStopY = -512
	#Replacement Block
	replacementBlock = "minecraft:air"

	[SETTINGS.Block-Update-Settings]
		#Call Neighbors
		notifyNeighbors = false
		#Update Block
		blockUpdate = true
		#Don't Update Renderer
		noRender = false
		#Do Update Renderer
		renderMainThread = false
		#Block Update Neighbors
		updateNeighbors = true

