
[ options ]
  # Defines the number of inventory slots that will be available.
  # Range: 1 ~ 36
  availableSlots = 18
  # Specifies a registry name for an item that on use would unlock a slot and consume the item, or nothing to not allow any item. Examples: minecraft:rabbit_foot, minecraft:nether_star, minestuck:captcha_card
  unlockSlotItem = "turkeydevutil:lanyard"
  # The number of unlocked slots that are relocked on death. If 0, slots will be unaffected by death. If -1, all unlocked slots will be relocked.
  # Range: -1 ~ 36
  unlockedLostOnDeath = 0
  # If true, items will be dropped when the slot they're in is locked. If false, the items will instead be moved to a locked inventory where they'll stay until the slot is unlocked again.
  dropItemsInLockedSlots = true
  # Specifies how the cost of unlocking a slot changes after each unlock. CONSTANT: 1, 1, 1... LINEAR: 1, 2, 3, 4... EXPONENTIAL: 1, 2, 4, 8, 16, 32, 64, after which no more slots can be unlocked.
  # Allowed Values: CONSTANT, LINEAR, EXPONENTIAL
  costProgression = "LINEAR"

