
[General]
	#A list of dimensions where there needs to be a bedrock floor
	flooredDimensions = ["minecraft:overworld", "minecraft:the_nether"]
	#A list of dimensions where there needs to be a bedrock roof
	roofedDimensions = ["minecraft:overworld", "minecraft:the_nether"]
	#Enable logging of the bedrock generation
	enableLogging = false

