
#Dirt Creeper Settings
["Dirt Creeper Settings"]
	#Spawn Dirt Creepers
	dirt_creeper_spawns = false
	#Dirt Creeper Group Minimum Size
	#Range: > 1
	dirt_creeper_min_spawn_size = 1
	#Dirt Creeper Group Maximum Size
	#Range: > 1
	dirt_creeper_max_spawn_size = 3
	#Dirt Creeper Weight (higher numbers = more)
	#Range: > 1
	dirt_creeper_weight = 20
	#Dirt Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	dirt_creeper_min_y = -64
	#Dirt Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	dirt_creeper_max_y = 688
	#Dirt Creeper Dimension Blacklist
	dirt_creeper_dimensions = []

#Stone Creeper Settings
["Stone Creeper Settings"]
	#Spawn Stone Creepers
	stone_creeper_spawns = false
	#Stone Creeper Group Minimum Size
	#Range: > 1
	stone_creeper_min_spawn_size = 1
	#Stone Creeper Group Maximum Size
	#Range: > 1
	stone_creeper_max_spawn_size = 3
	#Stone Creeper Weight (higher numbers = more)
	#Range: > 1
	stone_creeper_weight = 25
	#Stone Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	stone_creeper_min_y = -64
	#Stone Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	stone_creeper_max_y = 688
	#Stone Creeper Dimension Blacklist
	stone_creeper_dimensions = []

#Cluster Creeper Settings
["Cluster Creeper Settings"]
	#Spawn Cluster Creepers
	cluster_creeper_spawns = false
	#Cluster Creepers Can Spawn a random Super Charged Creeper
	cluster_creeper_sc_spawns = false
	#Random Super Charged Spawn Chance (lower = more)
	#Range: > 1
	cluster_creeper_sc_spawns_weight = 20
	#Cluster Creeper Group Minimum Size
	#Range: > 1
	cluster_creeper_min_spawn_size = 1
	#Cluster Creeper Group Maximum Size
	#Range: > 1
	cluster_creeper_max_spawn_size = 3
	#Cluster Creeper Weight (higher numbers = more)
	#Range: > 1
	cluster_creeper_weight = 25
	#Cluster Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	cluster_creeper_min_y = -64
	#Cluster Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	cluster_creeper_max_y = 688
	#Cluster Creeper Dimension Blacklist
	cluster_creeper_dimensions = []

#Super Charged Creeper Settings
["Super Charged Creeper Settings"]
	#Spawn Super Charged Creepers
	super_charged_creeper_spawns = false
	#Super Charged Creeper Group Minimum Size
	#Range: > 1
	super_charged_creeper_min_spawn_size = 1
	#Super Charged Creeper Group Maximum Size
	#Range: > 1
	super_charged_creeper_max_spawn_size = 3
	#Super Charged Creeper Weight (higher numbers = more)
	#Range: > 1
	super_charged_creeper_weight = 10
	#Super Charged Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	super_charged_creeper_min_y = -64
	#Super Charged Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	super_charged_creeper_max_y = 528
	#Super Charged Creeper Dimension Blacklist
	super_charged_creeper_dimensions = []
	#Super Charged Creeper Explosion Radius
	#Range: 1 ~ 32
	super_charged_creeper_explode_radius = 8

#Ambush Creeper Settings
["Ambush Creeper Settings"]
	#Spawn Ambush Creepers
	ambush_creeper_spawns = false
	#Ambush Creeper Group Minimum Size
	#Range: > 1
	ambush_creeper_min_spawn_size = 1
	#Ambush Creeper Group Maximum Size
	#Range: > 1
	ambush_creeper_max_spawn_size = 3
	#Ambush Creeper Weight (higher numbers = more)
	#Range: > 1
	ambush_creeper_weight = 15
	#Ambush Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	ambush_creeper_min_y = -64
	#Ambush Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	ambush_creeper_max_y = 688
	#Ambush Creeper Dimension Blacklist
	ambush_creeper_dimensions = []

#Dirt WaterCreeper Settings
["Dirt WaterCreeper Settings"]
	#Spawn Dirt Water Creepers
	dirt_water_creeper_spawns = false
	#Dirt Water Creeper Group Minimum Size
	#Range: > 1
	dirt_water_creeper_min_spawn_size = 1
	#Dirt Water Creeper Group Maximum Size
	#Range: > 1
	dirt_water_creeper_max_spawn_size = 3
	#Dirt Water Creeper Weight (higher numbers = more)
	#Range: > 1
	dirt_water_creeper_weight = 20
	#Dirt Water Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	dirt_water_creeper_min_y = -64
	#Dirt Water Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	dirt_water_creeper_max_y = 319
	#Dirt Water Creeper Dimension Blacklist
	dirt_water_creeper_dimensions = []

#Stone Lava Creeper Settings
["Stone Lava Creeper Settings"]
	#Spawn Stone Lava Creepers
	stone_creeper_spawns = false
	#Stone Lava Creeper Group Minimum Size
	#Range: > 1
	stone_lava_creeper_min_spawn_size = 1
	#Stone Lava Creeper Group Maximum Size
	#Range: > 1
	stone_lava_creeper_max_spawn_size = 3
	#Stone Lava Creeper Weight (higher numbers = more)
	#Range: > 1
	stone_lava_creeper_weight = 20
	#Stone Lava Creeper Min Y Spawn Height
	#Range: -2032 ~ 2032
	stone_lava_creeper_min_y = -64
	#Stone Lava Creeper Max Y Spawn Height
	#Range: -2032 ~ 2032
	stone_lava_creeper_max_y = 319
	#Stone Lava Creeper Dimension Blacklist
	stone_lava_creeper_dimensions = []

