#Enable the the spawning of enchanted mobs. [true / false]
"Enchanted Mob can Spawn Natural" = true
#Disables specific mob from receiveing enchantments on spawn. Use the full name, eg: minecraft:ender_dragon.
enchantOnSpawnExclusionMobs = ["minecraft:wither", "minecraft:ender_dragon"]
#Enable the the spawning of enchanted animal mobs. [true / false]
"Enchanted Animal can Spawn Natural" = false
#Enable enchanting yourself. [true / false]
"Enchant yourself" = true
#Allow the specific mob from alway receiveing enchantments on spawn. Use the full name, eg: minecraft:zombie.
alwayEnchantableMobs = []
#Enable Change Size When Enchanted. [true / false]
"Change Size" = true
#Enable Increase Health like Dungeons When Enchanted. [true / false]
"Increase Health like Dungeons" = false
#Disables the specific mob enchant. Use the full name(This config only disabled mob enchant when mob spawn. not mean delete complete, eg: enchantwithmob:thorn.
disableMobEnchants = []
#Enable Player More Bigger When You have Huge Enchant. [true / false]
"Big Your Self" = false

