
[HUD]
	#Delay between chunk data refreshes
	#Range: > 10
	chunkRendererDelay = 500
	#Radius used for debug chunk rendering
	#Range: > 1
	chunkRendererRadius = 5
	#Delay between entity HUD data refreshes
	#Range: > 10
	hudEntityDelay = 250

[Behavior]
	#Automatically copy items to clipboard when running commands to list them (mt hand/hot/inv/blockinv)
	autoCopyItems = true

