
#Command Settings
[commands]

	[commands.general]
		#Command messages show to all players on server.
		msgAllPlayers = false
		#Sets all command to be this permission level.
		#Range: 0 ~ 4
		cmdPermissionsLevel = 2
		#Commands show a message in chat.
		msgShow = true

	#InventoryBomb Command Settings
	[commands.InventoryBomb]
		#Item that will replace all inventory slots with after items are dropped
		inventoryBombItem = "minecraft:dead_bush"

	#DisconnectPlayer Command Settings
	[commands.DisconnectPlayer]
		#Message to show when disconnected
		disconnectMsg = " and had a Dark PANIC moment and some how left the server."

	#PlayerNudger Command Settings
	[commands.PlayerNudger]

		[commands.PlayerNudger.North]
			#Chance for playernudger command to nudge North
			#Range: 0 ~ 100
			North_Chance = 4
			#Strength of playernudger command nudging North
			#Range: 0.0 ~ 10.0
			North_Strength = 0.7

		[commands.PlayerNudger.NorthEast]
			#Chance for playernudger command to nudge Northeast
			#Range: 0 ~ 100
			Northeast_Chance = 2
			#Strength of playernudger command nudging Northeast
			#Range: 0.0 ~ 10.0
			Northeast_Strength = 0.7

		[commands.PlayerNudger.East]
			#Chance for playernudger command to nudge East
			#Range: 0 ~ 100
			East_Chance = 4
			#Strength of playernudger command nudging East
			#Range: 0.0 ~ 10.0
			East_Strength = 0.7

		[commands.PlayerNudger.SouthEast]
			#Chance for playernudger command to nudge Southeast
			#Range: 0 ~ 100
			SouthEast_Chance = 2
			#Strength of playernudger command nudging Southeast
			#Range: 0.0 ~ 10.0
			SouthEast_Strength = 0.7

		[commands.PlayerNudger.South]
			#Chance for playernudger command to nudge South
			#Range: 0 ~ 100
			South_Chance = 4
			#Strength of playernudger command nudging South
			#Range: 0.0 ~ 10.0
			South_Strength = 0.7

		[commands.PlayerNudger.SouthWest]
			#Chance for playernudger command to nudge Southwest
			#Range: 0 ~ 100
			SouthWest_Chance = 2
			#Strength of playernudger command nudging Southwest
			#Range: 0.0 ~ 10.0
			SouthWest_Strength = 0.7

		[commands.PlayerNudger.West]
			#Chance for playernudger command to nudge West
			#Range: 0 ~ 100
			West_Chance = 4
			#Strength of playernudger command nudging West
			#Range: 0.0 ~ 10.0
			West_Strength = 0.7

		[commands.PlayerNudger.NorthWest]
			#Chance for playernudger command to nudge Northwest
			#Range: 0 ~ 100
			NorthWest_Chance = 2
			#Strength of playernudger command nudging Northwest
			#Range: 0.0 ~ 10.0
			NorthWest_Strength = 0.7

		[commands.PlayerNudger.Up]
			#Chance for playernudger command to nudge Up
			#Range: 0 ~ 100
			Up_Chance = 1
			#Strength of playernudger command nudging Up
			#Range: 0.0 ~ 10.0
			Up_Strength = 0.7

		[commands.PlayerNudger.Down]
			#Chance for playernudger command to nudge Down
			#Range: 0 ~ 100
			Down_Chance = 0
			#Strength of playernudger command nudging Down
			#Range: 0.0 ~ 10.0
			Down_Strength = 0.7

		[commands.PlayerNudger.PlayerFacingDirections]
			#Multiplier to increase the chance to nudge where the player is looking
			#Range: 0 ~ 100
			Forward_Multiplier = 1
			#Multiplier to increase the chance to nudge opposite where the player is looking
			#Range: 0 ~ 100
			Backward_Multiplier = 1
			#Multiplier to increase the chance to nudge the player to the left
			#Range: 0 ~ 100
			Left_Multiplier = 1
			#Multiplier to increase the chance to nudge the player to the right
			#Range: 0 ~ 100
			Right_Multiplier = 1

	#RandomTeleport Command Settings
	[commands.RandomTeleport]

		[commands.RandomTeleport."X Axis"]
			#Miniumum X offset from original X level. (i.e. 10 means when teleported will be at least 10 blocks along the X axis from original position)
			#Range: 0 ~ 100000
			randomTeleportXMin = 100
			#Maximum X offset from original X level. (i.e. 100 means when teleported will be less than 100 blocks away on the X axis from original position)
			#Range: 0 ~ 100000
			randomTeleportXMax = 500

		[commands.RandomTeleport."Y Axis"]
			#Miniumum Y offset from original Y level. (i.e. 10 means when teleported will be at least 10 blocks higher or lower than original position)
			#Range: 0 ~ 30000000
			randomTeleportYMin = 1
			#Maximum Y offset from original Y level. (i.e. 100 means when teleported will be less than 100 blocks higher or lower than original position)
			#Range: 0 ~ 30000000
			randomTeleportYMax = 10

		[commands.RandomTeleport."Z Axis"]
			#Miniumum Z offset from original X level. (i.e. 10 means when teleported will be at least 10 blocks along the Z axis from original position)
			#Range: 0 ~ 100000
			randomTeleportZMin = 100
			#Maximum Z offset from original X level. (i.e. 100 means when teleported will be less than 100 blocks away on the Z axis from original position)
			#Range: 0 ~ 100000
			randomTeleportZMax = 500

	#QuickHide Command Settings
	[commands.QuickHide]
		#List of random options that can be chosen when using quickhide command
		QuickHideList = ["minecraft:dead_bush,quick hide in these bushes!", "minecraft:wheat,quick hide in the wheat field!", "minecraft:feather,quick act like a chicken!", "minecraft:painting,quick blend into the wall!"]

	#SummonMount Command Settings
	[commands.SummonMount]
		#List of Classifications for SummonMount command to INCLUDE from possible entities. Use "ANY" for all.
		SummonMountClass = ["ambient", "creature", "water_creature", "water_ambient", "monster"]
		#List of entities for SummonMount command to EXCLUDE from possible entities
		SummonMount = ["alexsmobs:void_portal", "alexsmobs:void_worm_part", "alexsmobs:void_worm_shot", "minecraft:area_effect_cloud", "minecraft:armor_stand", "minecraft:arrow", "minecraft:dragon_fireball", "minecraft:evoker_fangs", "minecraft:experience_orb", "minecraft:eye_of_ender", "minecraft:falling_block", "minecraft:firework_rocket", "minecraft:glow_item_frame", "minecraft:item", "minecraft:item_frame", "minecraft:fireball", "minecraft:leash_knot", "minecraft:llama_spit", "minecraft:marker", "minecraft:command_block_minecart", "minecraft:painting", "minecraft:shulker_bullet", "minecraft:small_fireball", "minecraft:snowball", "minecraft:spectral_arrow", "minecraft:egg", "minecraft:ender_pearl", "minecraft:experience_bottle", "minecraft:potion", "minecraft:trident", "minecraft:wither_skull", "minecraft:player", "minecraft:fishing_bobber", "create:super_glue", "create:crafting_blueprint", "create:contraption", "create:stationary_contraption", "create:gantry_contraption", "create:carriage_contraption", "create:potato_projectile", "create:seat", "gateways:gateway", "apotheosis:obsidian_arrow", "apotheosis:broadhead_arrow", "apotheosis:explosive_arrow", "apotheosis:mining_arrow", "glow_sticks:glow_stick", "glowinc:glow_ball_entity", "luggage:luggage", "projecte:fire_projectile", "projecte:homing_arrow", "projecte:lava_projectile", "projecte:lens_projectile", "projecte:mob_randomizer", "projecte:nova_catalyst_primed", "projecte:nova_cataclysm_primed", "projecte:swrg_projectile", "projecte:water_projectile", "cofh_core:knife", "cofh_core:electric_arc", "cofh_core:electric_field", "cofh_core:black_hole", "thermal:basalz_projectile", "thermal:blizz_projectile", "thermal:blitz_projectile", "thermal:explosive_grenade", "thermal:fire_grenade", "thermal:ice_grenade", "thermal:lightning_grenade", "thermal:earth_grenade", "thermal:ender_grenade", "thermal:glowstone_grenade", "thermal:redstone_grenade", "thermal:slime_grenade", "thermal:phyto_grenade", "thermal:nuke_grenade", "thermal:fire_tnt", "thermal:ice_tnt", "thermal:lightning_tnt", "thermal:earth_tnt", "thermal:ender_tnt", "thermal:glowstone_tnt", "thermal:redstone_tnt", "thermal:slime_tnt", "thermal:phyto_tnt", "thermal:nuke_tnt", "gravityforce:physics_block", "insanelib:area_effect_cloud_3d", "alexsmobs:bone_serpent_part", "alexsmobs:tossed_item", "alexsmobs:vine_lasso", "alexsmobs:anaconda_part", "alexsmobs:pollen_ball", "sophisticatedbackpacks:everlasting_backpack_item", "dirt_flinger:thrown_dirt", "adpother:purified_air", "adpother:gas", "farmersdelight:rotten_tomato", "eyesinthedarkness:eyes", "camera:image_frame", "delivery:drone", "cyclic:magic_net", "cyclic:torch_bolt", "cyclic:boomerang_stun", "cyclic:boomerang_carry", "cyclic:boomerang_damage", "cyclic:dungeon", "cyclic:eye", "cyclic:lightning_bolt", "cyclic:snow_bolt", "cyclic:fire_bolt", "cyclic:stone_bolt", "cyclic:laser_bolt", "cyclic:magic_missile", "cyclic:conveyor_item", "cyclic:darkfire_bolt", "cyclic:ender_fishing", "tconstruct:fancy_item_frame", "tconstruct:glow_ball", "tconstruct:efln_ball", "tconstruct:quartz_shuriken", "tconstruct:flint_shuriken", "tconstruct:indestructible_item", "dimpaintings:dimensional_painting", "minecraft:wither", "minecraft:ender_dragon", "alexsmobs:centipede_body", "alexsmobs:centipede_tail", "born_in_chaos_v1:decrepit_skeleton", "born_in_chaos_v1:skeleton_bomb", "born_in_chaos_v1:decaying_zombie", "born_in_chaos_v1:baby_skeleton", "born_in_chaos_v1:zombiesina_barrel", "born_in_chaos_v1:phantom_creeper", "born_in_chaos_v1:zombieswith_door", "born_in_chaos_v1:restless_spirit", "born_in_chaos_v1:skeleton_thrasher", "born_in_chaos_v1:pumpkin_spirit", "born_in_chaos_v1:seared_spirit", "born_in_chaos_v1:firelight", "born_in_chaos_v1:diamond_thermite", "born_in_chaos_v1:bonescaller", "born_in_chaos_v1:supreme_bonecaller", "born_in_chaos_v1:bone_imp", "born_in_chaos_v1:nightmare_stalker", "born_in_chaos_v1:dark_vortex", "born_in_chaos_v1:wither_strider", "born_in_chaos_v1:dread_hound", "born_in_chaos_v1:decrepit_skeleton_n", "born_in_chaos_v1:skeleton_bomb_n", "born_in_chaos_v1:decaying_zombie_n", "born_in_chaos_v1:baby_skeleton_n", "born_in_chaos_v1:phantom_creeper_n", "born_in_chaos_v1:zombieswith_door_n", "born_in_chaos_v1:restless_spirit_n", "born_in_chaos_v1:skeleton_thrasher_n", "born_in_chaos_v1:firelight_n", "born_in_chaos_v1:bonescaller_n", "born_in_chaos_v1:s_bonescaller_n", "born_in_chaos_v1:bone_imp_n", "born_in_chaos_v1:nightmare_stalker_n", "born_in_chaos_v1:dark_vortex_n", "born_in_chaos_v1:wither_strider_n", "born_in_chaos_v1:dread_hound_n", "born_in_chaos_v1:phantom_creeper_form", "born_in_chaos_v1:baby_skkl", "born_in_chaos_v1:baby_sk_pow", "born_in_chaos_v1:supreme_bonescaller_s_2", "born_in_chaos_v1:controlled_baby_skeleton", "born_in_chaos_v1:fallen_chaos_knight", "born_in_chaos_v1:fallenchaosknight_n", "born_in_chaos_v1:scarletpersecutor"]
		#Custom name for SummonMount entities.
		summonMountCustomName = true
		#Try to summon entity already tamed.
		summonMountTamed = true

	#SummonRider Command Settings
	[commands.SummonRider]
		#List of Classifications for SummonRide command to INCLUDE from possible entities. Use "ANY" for all.
		SummonRiderClass = ["ambient", "creature", "water_creature", "water_ambient"]

	#DisplayDeathBoard Command Settings
	[commands.DisplayDeathBoard]
		#List of strings to put at the end based on position. Ranks without a separate value will use whatever the last value is
		DisplayDeathBoard = [" rip"]

	#RandomGift Command Settings
	[commands.RandomGift]
		#List of items (resource location,amount,weighted chance) to be chosen for RandomGift command to choose from
		RandomGift = ["minecraft:diamond,1,1", "minecraft:feather,64,99"]

	#RandomTeleportDirection Command Settings
	[commands.RandomTeleportDirection]
		#Teleports user in a random direction with the given amount as distance from their original spot
		#Range: 0 ~ 100000
		RandomTeleportDirection = 500
		#Miniumum Y offset from original Y level. (i.e. 10 means when teleported will be at least 10 blocks higher or lower than original position
		#Range: 0 ~ 30000000
		randomTeleportdDirectionYMin = 0
		#Maximum Y offset from original Y level. (i.e. 100 means when teleported will be less than 100 blocks higher or lower than original position
		#Range: 0 ~ 30000000
		randomTeleportYDirectionMax = 320

	#RandomEnchanting Command Settings
	[commands.RandomEnchanting]
		#List of enchantment(s) for RandomEnchanting command to EXCLUDE from possible enchantments (i.e. minecraft:vanishing_curse)
		RandomEnchantingExclude = ["walljump:walljump"]
		#Force random enchantment on even if normally cannot go on item.
		randomEnchantForce = true

