
#General settings
[general]
	#Dictates whether or not the vanilla biome places are enabled
	enableBiomePlaces = false
	#Dictates whether or not the vanilla dimension places are enabled (excluding the Overworld)
	enableDimensionPlaces = true

