
# General settings
[ profiles ]
  # A list of dimensions with associated city generation profiles (format <dimensionid>=<profilename>
  dimensionsWithProfiles = ["minecraft:the_overworld=underground"]

