#Show the debug info
SHOW_DEBUG = false

#If SHOW_DEBUG is set to true, but you only want to see the song name
CURRENT_SONG_ONLY = false

#The lowest level of logging (DEBUG/INFO/WARN/ERROR/FATAL) to include in the GUI log visualizer
LOG_LEVEL = "INFO"

#Allows vanilla and blocked music to play when there is music from Music Triggers already playing
PLAY_NORMAL_MUSIC = false

#Reverses the priority checker in the case of multiple triggers being able to play at once so the lowest priority wins instead of the highest
REVERSE_PRIORITY = false

#Allows for the combination of song pools in the case of multiple triggers with the same priority value being able to play at once
COMBINE_EQUAL_PRIORITY = false

#If PAUSE_WHEN_TABBED is set to false, the music will no longer get paused when the game is not in focus
PAUSE_WHEN_TABBED = true

#A list of mod ids to block audio in the Music category from so there is no overlap in music playing during events from other mods
BLOCKED_MOD_MUSIC = [ ]

#A list of mod ids to block audio in the Records category from so there is no overlap in records playing during events from other mods
BLOCKED_MOD_RECORDS = [ ]
