[[horror_intro]]
	pitch = "1.0"
	volume = "0.2"
	play_once = "2"

	[horror_intro.trigger]
		name = "menu"

[[sewer_ambience]]
	volume = "0.05"

	[sewer_ambience.trigger]
		name = "zones"
		identifier = "sewer_ambience"
		fade_in = "40"
		fade_out = "40"
		time = "80"

		[sewer_ambience.trigger.zone]
			x_min = "-30000000"
			y_min = "0"
			z_min = "-30000000"
			x_max = "30000000"
			y_max = "20"
			z_max = "30000000"

[[underwater_ambience]]
	volume = "1.0"

	[underwater_ambience.trigger]
		name = "zones"
		identifier = "underwater_ambience"
		fade_in = "40"
		fade_out = "40"
		time = "80"

		[underwater_ambience.trigger.zone]
			x_min = "-30000000"
			y_min = "20"
			z_min = "-30000000"
			x_max = "30000000"
			y_max = "132"
			z_max = "30000000"

[[castle_ambience]]
	volume = "1.0"

	[castle_ambience.trigger]
		name = "zones"
		identifier = "castle_ambience"
		fade_in = "40"
		fade_out = "40"
		time = "80"

		[castle_ambience.trigger.zone]
			x_min = "-30000000"
			y_min = "133"
			z_min = "-30000000"
			x_max = "30000000"
			y_max = "264"
			z_max = "30000000"

[[greed_ambience]]
	volume = "1.0"

	[greed_ambience.trigger]
		name = "zones"
		identifier = "greed_ambience"
		fade_in = "40"
		fade_out = "40"
		time = "80"

		[greed_ambience.trigger.zone]
			x_min = "-30000000"
			y_min = "133"
			z_min = "-30000000"
			x_max = "30000000"
			y_max = "264"
			z_max = "30000000"

[[soulsand_valley_ambience]]
	volume = "0.2"

	[soulsand_valley_ambience.trigger]
		name = "zones"
		identifier = "soulsand_valley_ambience"
		fade_in = "40"
		fade_out = "40"
		time = "80"

		[soulsand_valley_ambience.trigger.zone]
			x_min = "-30000000"
			y_min = "397"
			z_min = "-30000000"
			x_max = "30000000"
			y_max = "528"
			z_max = "30000000"

[[limbo_ambience]]
	volume = "0.75"

	[limbo_ambience.trigger]
		name = "zones"
		identifier = "limbo_ambience"
		fade_in = "40"
		fade_out = "40"
		time = "80"

		[limbo_ambience.trigger.zone]
			x_min = "-30000000"
			y_min = "528"
			z_min = "-30000000"
			x_max = "30000000"
			y_max = "688"
			z_max = "30000000"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_wither"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Wither"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_webber"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Webber"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_poisonous"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Poisonous"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_1up"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "1UP"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_blastoff"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Blastoff"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_fiery"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Fiery"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_rust"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Rust"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_alchemist"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Alchemist"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_lifesteal"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Lifesteal"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_weakness"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Weakness"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_ghastly"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Ghastly"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_ninja"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Ninja"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_bulwark"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Bulwark"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_exhaust"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Exhaust"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_darkness"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Darkness"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_ender"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Ender"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_gravity"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Gravity"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_choke"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Choke"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_quicksand"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Quicksand"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_storm"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Storm"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_berserk"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Berserk"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_vengeance"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Vengeance"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_regen"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Regen"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_sapper"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Sapper"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_sprint"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Sprint"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_cloaking"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Cloaking"

[[infernal_music]]
	volume = "0.5"

	[infernal_music.trigger]
		name = "mob"
		identifier = "infernal_music_sticky"
		fade_in = "40"
		fade_out = "40"
		time = "80"
		detection_range = "32"
		mob_targeting = "true"
		infernal = "Sticky"

