
# Dimension settings
[ Dimension ]
  # Setting this to true will prevent players from teleporting to the dimension
  disableTeleporter = true

# Biome settings
[ Biome ]
  # Overworld cotton candy plains biome weight. 0 to prevent generation in overworld
  # Range: > 0
  weightCottonCandyPlains = 0
  # Overworld chocolate forest biome weight. 0 to prevent generation in overworld
  # Range: > 0
  weightChocolateForest = 0
  # Overworld gummy swamp biome weight. 0 to prevent generation in overworld
  # Range: > 0
  weightGummySwamp = 0

# Mob settings
[ Mobs ]
  # Cotton candy sheep weight. 0 to prevent spawning
  # Range: > 1
  weightCottonCandySheep = 1
  # Easter chicken weight. 0 to prevent spawning
  # Range: > 1
  weightEasterChicken = 1
  # Gummy mice weight. 0 to prevent spawning
  # Range: > 1
  weightGummyMouse = 1
  # Gummy bear weight. 0 to prevent spawning
  # Range: > 1
  weightGummyBear = 1
  # setting this to true should prevent any non-Candy World mobs from spawning in candy world biomes
  preventModdedMobSpawn = true

# General settings
[ General ]
  # Setting this to true will make tree trunks take longer to mine the higher they are
  recursiveTreeTrunks = false
  # Setting this to false will make tree trunk blocks behave like normal blocks
  stackableTreeTrunks = false

