
#Friends
[friends]
	#A list of users who can be chosen when it spawns a distant friend
	friends = ["blargerist"]

#Spawning
[spawning]
	#The spawning weight of Friend's (0 = disabled) [default: 20]
	#Range: > 0
	friendWeight = 7
	#The minimum number of Friend's in a group [default:1]
	#Range: > 1
	friendMinGroup = 1
	#The maximum number of Friend's in a group [default: 2]
	#Range: > 1
	friendMaxGroup = 1

#Compat
[compat]
	#Add players from a Player Mobs whitelist to the Friends list [default: false]
	playerMobsCompat = true
	#The player mobs Name Links
	playerMobsWhitelist = ["https://whitelist.gorymoon.se/list/RBaEKlLZbgrX39xp0vmdr/minecraft_twitch_nl"]

