"Show Enchanted Mob Hud" = true
#Disable Poison Mob Enchant Particle. [true / false]
"Disable Poison Particle" = true
#Disable Aura Render. [true / false]
"Disable Aura Render" = true
#Sets the intensity of glint. [true / false]
#Range: 0.1 ~ 1.0
"Glint Percent" = 0.5

