
#General settings
[General]
	#Mobs that are exempt from AI modifications [default: [minecraft:iron_golem]
	AI_Blacklist = ["adpother:gas", "adpother:purified_air", "alexsmobs:anaconda_part", "alexsmobs:anteater", "alexsmobs:bison", "alexsmobs:blobfish", "alexsmobs:bone_serpent", "alexsmobs:bone_serpent_part", "alexsmobs:bunfungus", "alexsmobs:cachalot_echo", "alexsmobs:cachalot_whale", "alexsmobs:centipede_body", "alexsmobs:centipede_head", "alexsmobs:centipede_tail", "alexsmobs:cockroach", "alexsmobs:cockroach_egg", "alexsmobs:comb_jelly", "alexsmobs:cosmaw", "alexsmobs:cosmic_cod", "alexsmobs:crow", "alexsmobs:dropbear", "alexsmobs:elephant", "alexsmobs:emu", "alexsmobs:emu_egg", "alexsmobs:enderiophage", "alexsmobs:enderiophage_rocket", "alexsmobs:flutter", "alexsmobs:fly", "alexsmobs:flying_fish", "alexsmobs:froststalker", "alexsmobs:gazelle", "alexsmobs:gelada_monkey", "alexsmobs:gust", "alexsmobs:hemolymph", "alexsmobs:hummingbird", "alexsmobs:ice_shard", "alexsmobs:jerboa", "alexsmobs:kangaroo", "alexsmobs:lobster", "alexsmobs:maned_wolf", "alexsmobs:mimic_octopus", "alexsmobs:mimicube", "alexsmobs:moose", "alexsmobs:mosquito_spit", "alexsmobs:mungus", "alexsmobs:orca", "alexsmobs:platypus", "alexsmobs:pollen_ball", "alexsmobs:raccoon", "alexsmobs:roadrunner", "alexsmobs:sand_shot", "alexsmobs:seagull", "alexsmobs:seal", "alexsmobs:shark_tooth_arrow", "alexsmobs:shoebill", "alexsmobs:skelewag", "alexsmobs:soul_vulture", "alexsmobs:straddleboard", "alexsmobs:straddler", "alexsmobs:stradpole", "alexsmobs:sunbird", "alexsmobs:terrapin", "alexsmobs:tossed_item", "alexsmobs:toucan", "alexsmobs:tusklin", "alexsmobs:vine_lasso", "alexsmobs:void_portal", "alexsmobs:void_worm", "alexsmobs:void_worm_part", "alexsmobs:void_worm_shot", "alexsmobs:warped_mosco", "apotheosis:broadhead_arrow", "apotheosis:explosive_arrow", "apotheosis:mining_arrow", "apotheosis:obsidian_arrow", "buddycards:enderling", "camera:image_frame", "candyworld:cotton_candy_sheep", "candyworld:easter_chicken", "candyworld:gummy_bear", "candyworld:gummy_mouse", "cofh_core:electric_arc", "cofh_core:electric_field", "cofh_core:knife", "core_creepers:super_charged_creeper", "create:carriage_contraption", "create:contraption", "create:crafting_blueprint", "create:gantry_contraption", "create:potato_projectile", "create:seat", "create:stationary_contraption", "create:super_glue", "cyclic:boomerang_carry", "cyclic:boomerang_damage", "cyclic:boomerang_stun", "cyclic:conveyor_item", "cyclic:darkfire_bolt", "cyclic:dungeon", "cyclic:ender_fishing", "cyclic:eye", "cyclic:fire_bolt", "cyclic:laser_bolt", "cyclic:lightning_bolt", "cyclic:magic_missile", "cyclic:magic_net", "cyclic:snow_bolt", "cyclic:stone_bolt", "cyclic:torch_bolt", "dabomb:bee_bomb", "dabomb:bomb", "dabomb:bomb_fish", "dabomb:bouncy_bomb", "dabomb:bouncy_dynamite", "dabomb:c4", "dabomb:dirt_bomb", "dabomb:dry_bomb", "dabomb:dynamite", "dabomb:ender_bomb", "dabomb:flower_bomb", "dabomb:lava_bomb", "dabomb:sticky_bomb", "dabomb:sticky_dynamite", "dabomb:water_bomb", "delivery:drone1", "dimpaintings:dimensional_painting", "dirt_flinger:thrown_dirt", "distantfriends:friend", "eyesinthedarkness:eyes", "farmersdelight:rotten_tomato", "gateways:gateway", "glow_sticks:glow_stick", "glowinc:glow_ball_entity", "goblintraders:goblin_trader", "goblintraders:vein_goblin_trader", "graveyard:skull", "gravityforce:physics_block", "hangman:camera", "hangman:hang_dummy", "impostore:impost_ore", "insanelib:area_effect_cloud_3d", "kobolds:kobold", "kobolds:kobold_captain", "kobolds:kobold_child", "kobolds:kobold_enchanter", "kobolds:kobold_engineer", "kobolds:kobold_pirate", "kobolds:kobold_warrior", "luggage:luggage", "magma_monsters:magma_monster", "magma_monsters:magma_monster_grunt", "minecraft:area_effect_cloud", "minecraft:armor_stand", "minecraft:arrow", "minecraft:axolotl", "minecraft:bat", "minecraft:bee", "minecraft:boat", "minecraft:cat", "minecraft:chest_minecart", "minecraft:chicken", "minecraft:cod", "minecraft:command_block_minecart", "minecraft:cow", "minecraft:dolphin", "minecraft:donkey", "minecraft:dragon_fireball", "minecraft:egg", "minecraft:end_crystal", "minecraft:ender_dragon", "minecraft:ender_pearl", "minecraft:enderman", "minecraft:evoker_fangs", "minecraft:experience_bottle", "minecraft:experience_orb", "minecraft:eye_of_ender", "minecraft:falling_block", "minecraft:fireball", "minecraft:firework_rocket", "minecraft:fishing_bobber", "minecraft:fox", "minecraft:furnace_minecart", "minecraft:giant", "minecraft:glow_item_frame", "minecraft:glow_squid", "minecraft:goat", "minecraft:hopper_minecart", "minecraft:horse", "minecraft:iron_golem", "minecraft:item", "minecraft:item_frame", "minecraft:leash_knot", "minecraft:lightning_bolt", "minecraft:llama", "minecraft:llama_spit", "minecraft:magma_cube", "minecraft:marker", "minecraft:minecart", "minecraft:mooshroom", "minecraft:mule", "minecraft:ocelot", "minecraft:painting", "minecraft:panda", "minecraft:parrot", "minecraft:phantom", "minecraft:pig", "minecraft:player", "minecraft:polar_bear", "minecraft:potion", "minecraft:pufferfish", "minecraft:rabbit", "minecraft:salmon", "minecraft:sheep", "minecraft:shulker", "minecraft:shulker_bullet", "minecraft:skeleton_horse", "minecraft:slime", "minecraft:small_fireball", "minecraft:snow_golem", "minecraft:snowball", "minecraft:spawner_minecart", "minecraft:spectral_arrow", "minecraft:squid", "minecraft:strider", "minecraft:tnt", "minecraft:tnt_minecart", "minecraft:trader_llama", "minecraft:trident", "minecraft:tropical_fish", "minecraft:turtle", "minecraft:villager", "minecraft:wandering_trader", "minecraft:wither_skull", "minecraft:wolf", "projecte:fire_projectile", "projecte:homing_arrow", "projecte:lava_projectile", "projecte:lens_projectile", "projecte:mob_randomizer", "projecte:nova_cataclysm_primed", "projecte:nova_catalyst_primed", "projecte:swrg_projectile", "projecte:water_projectile", "sophisticatedbackpacks:everlasting_backpack_item", "strawgolem:strawgolem", "strawgolem:strawnggolem", "tconstruct:earth_slime", "tconstruct:efln_ball", "tconstruct:ender_slime", "tconstruct:fancy_item_frame", "tconstruct:flint_shuriken", "tconstruct:glow_ball", "tconstruct:indestructible_item", "tconstruct:quartz_shuriken", "tconstruct:sky_slime", "tconstruct:terracube", "thermal:basalz_projectile", "thermal:blitz_projectile", "thermal:blizz_projectile", "thermal:earth_grenade", "thermal:earth_tnt", "thermal:ender_grenade", "thermal:ender_tnt", "thermal:explosive_grenade", "thermal:fire_grenade", "thermal:fire_tnt", "thermal:glowstone_grenade", "thermal:glowstone_tnt", "thermal:ice_grenade", "thermal:ice_tnt", "thermal:lightning_grenade", "thermal:lightning_tnt", "thermal:nuke_grenade", "thermal:nuke_tnt", "thermal:phyto_grenade", "thermal:phyto_tnt", "thermal:redstone_grenade", "thermal:redstone_tnt", "thermal:slime_grenade", "thermal:slime_tnt", "tntslimes:tnt_slime", "turkeydevutil:duck", "turkeydevutil:turkey", "waddles:adelie_penguin", "mowziesmobs:foliaath", "mowziesmobs:baby_foliaath", "mowziesmobs:ferrous_wroughtnaut", "mowziesmobs:barakoan_barakoana", "mowziesmobs:barakoan_player", "mowziesmobs:barakoa_sunblocker_player", "mowziesmobs:barakoaya", "mowziesmobs:barakoana", "mowziesmobs:barakoa_sunblocker", "mowziesmobs:barako", "mowziesmobs:frostmaw", "mowziesmobs:grottol", "mowziesmobs:lantern", "mowziesmobs:naga", "mowziesmobs:sunstrike", "mowziesmobs:solar_beam", "mowziesmobs:boulder_projectile", "mowziesmobs:boulder_platform", "mowziesmobs:pillar", "mowziesmobs:pillar_piece", "mowziesmobs:axe_attack", "mowziesmobs:ice_breath", "mowziesmobs:ice_ball", "mowziesmobs:frozen_controller", "mowziesmobs:dart", "mowziesmobs:poison_ball", "mowziesmobs:super_nova", "mowziesmobs:falling_block", "mowziesmobs:block_swapper", "mowziesmobs:camera_shake"]
	#Prevents players skipping the night through sleep [default: false]
	allowSleep = false
	#Awareness Radius [default: 64]
	#Range: > 0
	awarenessRadius = 40
	#The interval in which 'hard' days will occur where mob spawning is increased and lighting is ignored (0 = off, default = 8/full moon) [default: 8]
	#Range: > 0
	hardcoreDayCycle = 0
	#Maximum number of attackers per target [default: 16]
	#Range: 0 ~ 128
	pathingCap = 16
	#Temporary invulnerability in ticks when respawning and teleporting [default: 200]
	#Range: > 0
	resistanceCooldown = 600
	#Xray Distance [default: 64]
	#Range: > 0
	xrayDistance = 40

#Attack settings
[Attack]
	#Allows mobs to attack villagers as they would players [default: true]
	attackPets = true
	#Everyone one and everything is a target [default: false]
	attackEverything = false
	#Mobs are passive until provoked [default: false]
	neutralMobs = false
	#Mobs will strafe more than normal and avoid imminent explosions [default: true]
	attackEvasion = true
	#Animals will fight back if provoked [default: true]
	animalsAttack = true

#Advanced settings
[Advanced]
	#List of mobs that can dig through blocks [default: [minecraft:zombie]
	diggerMobs = ["alexsmobs:leafcutter_ant", "minecraft:zombie", "player_mobs:player_mob", "graveyard:ghoul", "graveyard:revenant", "kobolds:kobold_zombie", "kobolds:kobold_zombie_drowned"]
	#List of blocks that digger mobs are forbidden from digging (Format: 'minecraft:wool' prefix with # if mentioning a block tag)
	diggingBlacklist = []
	#Is the digging blacklist inverted? [default: false]
	diggingBlacklistInverted = false
	#Digging mobs require the proper tools to dig [default: true]
	diggingRequiresTools = true
	#How common demolition variants are [default: 0.1]
	#Range: 0.0 ~ 1.0
	demolitionChance = 0.05
	#List of mobs that can drop live TNT [default: [minecraft:zombie]
	demolitionMobs = ["minecraft:zombie", "player_mobs:player_mob", "graveyard:nightmare"]
	#List of mobs that can pillar up and build stairs [default: [minecraft:zombie]
	buildingMobs = ["minecraft:zombie", "player_mobs:player_mob", "graveyard:nightmare"]
	#If mobs should be allowed to grief blocks [default: false]
	griefing = true
	#What blocks will be targeted for destruction when idle (Format: 'minecraft:wool' prefix with # if mentioning a block tag)
	griefableBlocks = ["#forge:glass", "#forge:glass_panes", "#forge:stained_glass", "#forge:stained_glass_panes", "#minecraft:crops", "#minecraft:fence_gates", "#minecraft:fences", "#minecraft:saplings", "#minecraft:wooden_doors", "minecraft:bookshelf", "minecraft:brewing_stand", "minecraft:cake", "minecraft:crafting_table", "minecraft:enchanting_table", "minecraft:farmland", "minecraft:ladder", "minecraft:melon_block", "minecraft:pumpkin", "minecraft:torch", "minecraft:redstone_torch", "minecraft:soul_torch"]
	#List of blocks that mobs can pillar with [default: [minecraft:cobblestone]
	pillarBlocks = ["minecraft:cobblestone"]
	#If mobs should be allowed to grief all light emitting blocks [default: true]
	griefLightSources = false
	#The item given to a digger 5% of the time [default: minecraft:iron_pickaxe]
	diggerItem = "tconstruct:pickaxe{tic_materials:[\"tconstruct:iron\",\"tconstruct:iron\",\"tconstruct:iron\"],tic_modifiers:[{level:1s,name:\"tconstruct:piercing\"},{level:3s,name:\"tconstruct:sturdy\"}],tic_persistent_data:{abilities:1,upgrades:3}}"

#Other settings
[Other]
	#Can fix some issues with long distance navigation pathing through unloaded chunks [default: true]
	altChunkCaching = true
	#The factor by which mob health and damage multipliers will be increased when bosses are killed [default: 0.1]
	#Range: 0.0 ~ 1.7976931348623157E308
	bossKillModifier = 0.1
	#The upper limit of the Boss Kill Modifier [default: 3.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	bossModifierCap = 3.0
	#Debug mob targeting by printing the targeting out [default: false]
	debugTargets = false
	#List of custom potion types witches can throw (id:duration:lvl) [default: [minecraft:harming:1:0, minecraft:slowness:200:0, minecraft:blindness:200:0, minecraft:poison:200:0, minecraft:weakness:200:1, minecraft:mining_fatigue:200:2] ]
	witchPotions = ["tconstruct:glow", "minecraft:harming:1:0", "minecraft:slowness:200:0", "minecraft:blindness:200:0", "minecraft:poison:200:0", "minecraft:weakness:200:1", "minecraft:mining_fatigue:200:2"]
	#Allows Enderman to teleport the player instead of themselves [default: true]
	enderPlayerTeleport = false
	#The chance a Spider will web its target to the ground [default: 0.25]
	#Range: 0.0 ~ 1.0
	webbingChance = 0.25
	#Dying to zombies will turn your corpse into one of them [default: true]
	infectiousZombies = false

#Creeper settings
[Creepers]
	#Ignores the listing and allows any mob to have a Creeper rider [default: true]
	allCreeperJockeys = true
	#Creepers will attempt to blast through walls [default: true]
	breaching = true
	#AND HIS NAME IS... [default: 0.01]
	#Range: 0.0 ~ 1.0
	cenaChance = 0.005
	#The chance a Creeper will spawn riding another mob [default: 0.1]
	#Range: 0.0 ~ 1.0
	creeperJockeyChance = 0.04
	#A list of mobs which can become Creeper Jockeys
	creeperJockeyMobs = ["minecraft:zombie", "player_mobs:player_mob", "minecraft:creeper", "minecraft:skeleton", "minecraft:spider", "kobolds:kobold_zombie", "kobolds:kobold_zombie_drowned", "kobolds:kobold_skeleton"]
	#Creeper detonations leave behind flaming craters [default: true]
	napalm = true
	#A list of mobs which when exploded generate napalm
	napalmMobs = ["minecraft:creeper", "core_creepers:cluster_creeper", "core_creepers:super_charged_creeper", "core_creepers:ambush_creeper", "graveyard:skeleton_creeper"]
	#The chance a Creeper will spawn pre-powered [default: 0.1]
	#Range: 0.0 ~ 1.0
	poweredRarity = 0.01
	#Creepers will continue approaching their target while arming [default: true]
	walkingFuse = true

#Skeletons settings
[Skeletons]
	#How likely Skeletons are to miss their target [default: 0]
	#Range: > 0
	arrowError = 2
	#How far away can Skeletons shoot from [default: 64]
	#Range: > 1
	fireDistance = 56
	#How far away can Skeletons shoot from [default: 64]
	#Range: 0.0 ~ 1.0
	witherSkeletonChance = 0.1
	#Effects that Skeleton arrows can have (id:duration:lvl) [default: [minecraft:slowness:60:0]
	arrowTips = ["minecraft:slowness:60:0"]

#Attribute settings
[Attributes]
	#Health modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	healthModifier = 1.0
	#Damage modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	damageModifier = 1.0
	#Speed modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	speedModifier = 1.0
	#Knockback modifier [default: 1.0]
	#Range: 0.0 ~ 1.7976931348623157E308
	knockbackModifier = 1.0
	#Boss Health modifier [default: false]
	bossHealthModifier = false
	#Boss Damage modifier [default: false]
	bossDamageModifier = false
	#Boss Speed modifier [default: false]
	bossSpeedModifier = false
	#Boss Knockback modifier [default: false]
	bossKnockbackModifier = false

#Game Stages support
[GameStages]
	#The stage required until mobs can dig through blocks [empty = disabled]
	diggerStage = "esm_2"
	#The stage required until mobs can drop live TNT [empty = disabled]
	demolitionStage = "esm_2"
	#The stage required until mobs can pillar up and build stairs [empty = disabled]
	buildingStage = "esm_1"
	#The stage required until mobs can grief blocks [empty = disabled]
	griefingStage = "esm_1"
	#The stage required until creeper jockeys can spawn [empty = disabled]
	creeperJockeyStage = "esm_2"

