
#Glow Ball
[glow_ball]
	#Whether the Glow Ball splat will disappear, regardless of the glowSplatMinutes.
	glowSplatPersistent = false
	#Number of minutes the Glow Ball splat will last.
	#Ignored if glowSplatPersistent is to set to true.
	#Range: 1 ~ 120
	glowSplatMinutes = 20

