
#Welcome to The Graveyard Config!
#
#Structures:
#Configure separation (Minimum distance between two structures of this type in chunks. Must be less than spacing).
#Configure spacing (Average distance between two structure placement attempts of this type in chunks).
#Configure whitelist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
#Configure blacklist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
#Configure mod whitelist: use "#modid" to whitelist the biomes of the specified mod for structures to spawn in (examples: #minecraft, #graveyard, #graveyard_biomes, #terralith, #byg, #bop).
#Valid vanilla biome categories are: #taiga, #extreme_hills, #jungle, #mesa, #plains, #savanna, #icy, #beach, #forest, #desert, #swamp, #mushroom, #underground, #mountain.
#A full list of all the biomes can be found here https:minecraft.fandom.com/wiki/Biome#Biome_IDs.
#
#Mobs:
#Configure spawning weight and group size of the spawn.
#Configure if mobs burn in sunlight and/or if mobs are affected by the wither effect.
#Configure whitelist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
#Configure blacklist: use "#biomeCategory" for biome categories and "minecraft:biome" for biomes (mod identifier + ":" + biome name).
#Configure mod whitelist: use "#modid" to whitelist the biomes of the specified mod for structures to spawn in (examples: #minecraft, #graveyard, #graveyard_biomes, #terralith, #byg, #bop).
#
#Additional:
#Configure graveyard fog particles rising from moss and set the chance of spawning them (higher numbers = lower chance of spawning).
#Configure if hordes of graveyard mobs can spawn and set their size and frequency.
#Configure if urns have a double chest inventory.
#
["The Graveyard - Structures Config"]

	["The Graveyard - Structures Config".small_graveyard]
		#Range: 0 ~ 200
		spacing = 20
		#Range: 0 ~ 200
		separation = 18
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 240451934
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_desert_graveyard]
		#Range: 0 ~ 200
		spacing = 32
		#Range: 0 ~ 200
		separation = 28
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 598017285
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_grave]
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 8
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 8675309
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_desert_grave]
		#Range: 0 ~ 200
		spacing = 20
		#Range: 0 ~ 200
		separation = 16
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 681236914
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_savanna_grave]
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 8
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 709787761
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".small_mountain_grave]
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 8
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 725689810
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".mushroom_grave]
		#Range: 0 ~ 200
		spacing = 24
		#Range: 0 ~ 200
		separation = 18
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 379123039
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".memorial_tree]
		#Range: 0 ~ 200
		spacing = 14
		#Range: 0 ~ 200
		separation = 12
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 529239621
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".medium_graveyard]
		#Range: 0 ~ 200
		spacing = 18
		#Range: 0 ~ 200
		separation = 16
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 1690192399
		whitelist = ["#forest"]
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".large_graveyard]
		#Range: 0 ~ 200
		spacing = 12
		#Range: 0 ~ 200
		separation = 10
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 304812394
		whitelist = []
		blacklist = []
		modWhitelist = ["#minecraft", "#graveyard_biomes"]
		canSpawnMobs = false

	["The Graveyard - Structures Config".haunted_house]
		#Range: 0 ~ 200
		spacing = 25
		#Range: 0 ~ 200
		separation = 20
		canGenerate = false
		#Range: 0 ~ 10000000000
		salt = 451235912
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".giant_mushroom]
		canGenerate = false
		#Range: 0 ~ 200
		spacing = 20
		#Range: 0 ~ 200
		separation = 18
		#Range: 0 ~ 10000000000
		salt = 365012356
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".altar]
		canGenerate = false
		#Range: 0 ~ 200
		spacing = 30
		#Range: 0 ~ 200
		separation = 24
		#Range: 0 ~ 10000000000
		salt = 1093123913
		whitelist = []
		blacklist = []
		modWhitelist = []
		canSpawnMobs = false

	["The Graveyard - Structures Config".crypt]
		canGenerate = false
		#Range: 0 ~ 200
		spacing = 24
		#Range: 0 ~ 200
		separation = 20
		#Range: 0 ~ 10000000000
		salt = 893183913
		whitelist = ["#underground"]
		blacklist = []
		modWhitelist = ["#minecraft"]
		canSpawnMobs = false

["The Graveyard - Mob Spawning Config"]

	["The Graveyard - Mob Spawning Config".ghoul]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeGhoul = 2
		#Range: 1 ~ 100
		maxGroupSizeGhoul = 5
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = []
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".revenant]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeRevenant = 1
		#Range: 1 ~ 100
		maxGroupSizeRevenant = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = []
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".reaper]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeReaper = 1
		#Range: 1 ~ 100
		maxGroupSizeGhoul = 1
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["graveyard_biomes:eroded_haunted_forest"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".nightmare]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeNightmare = 1
		#Range: 1 ~ 100
		maxGroupSizeNightmare = 1
		canBurnInSunlight = false
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".skeleton_creeper]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeSkeletonCreeper = 1
		#Range: 1 ~ 100
		maxGroupSizeSkeletonCreeper = 4
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".acolyte]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeAcolyte = 2
		#Range: 1 ~ 100
		maxGroupSizeAcolyte = 3
		canBurnInSunlight = false
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".wraith]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeWraith = 2
		#Range: 1 ~ 100
		maxGroupSizeWraith = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".corruptedPillager]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeCorruptedPillager = 2
		#Range: 1 ~ 100
		maxGroupSizeCorruptedPillager = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

	["The Graveyard - Mob Spawning Config".corruptedVindicator]
		enabled = false
		#Range: 0 ~ 100
		weight = 0
		#Range: 1 ~ 100
		minGroupSizeCorruptedVindicator = 2
		#Range: 1 ~ 100
		maxGroupSizeCorruptedVindicator = 3
		canBurnInSunlight = true
		canBeWithered = false
		whitelist = ["#taiga", "#extreme_hills", "#jungle", "#mesa", "#plains", "#savanna", "#icy", "#beach", "#forest", "#desert", "#swamp", "#underground", "#mountain"]
		blacklist = ["minecraft:flower_forest", "minecraft:lush_caves"]
		modWhitelist = ["#minecraft", "#graveyard_biomes"]

["The Graveyard - Horde Config"]

	["The Graveyard - Horde Config".horde]
		generate = false
		#Range: 1 ~ 1000000
		ticksUntilSpawnHorde = 288000
		#Range: 0 ~ 1000
		mobSpawnAttempts = 40
		#Range: 1 ~ 1000000
		additionalRandomizedTicks = 120000

["The Graveyard - Particle Config"]

	["The Graveyard - Particle Config".particle]
		generate = true
		#Range: 1 ~ 500
		frequency = 50

["The Graveyard - Additional Config"]

	["The Graveyard - Additional Config".urn]
		urnHasDoubleInventory = true

	["The Graveyard - Additional Config".terrain]
		#Range: 1 ~ 100
		maxTerrainHeightDifference = 6

	["The Graveyard - Additional Config".spawner]
		disableWitherSkeletonSpawner = false

