
[world_creation_settings]
	#The directory of the world template
	template_directory = "template"
	#Whether a template should be used instead of creating regular worlds
	use_template = false
	#Whether to use the world settings from the template and ignore player changes
	use_template_world_settings = false

[world_creation_menu_settings]
	#Toggle the game mode button
	disable_game_mode = false
	#Toggle the cheats button
	disable_cheats = false
	#Toggle the game rules button
	disable_game_rules = true
	#Toggle the difficulty button
	disable_difficulty = false
	#Toggle the data packs button
	disable_data_packs = true
	#Toggle the more world options button
	disable_more_world_options = true

[main_menu_settings]
	#Toggle the multiplayer button
	disable_multiplayer = false
	#Toggle the singleplayer button
	disable_singleplayer = false

