
[ "Get New Curios Slot %" ]
  # Range: 0 ~ 100
  "new slot probability" = 100

[ "Rage Mind Particles" ]
  "Show particles?" = false

[ "Get fragments by destroying Trinkets?" ]
  "Get Fragments?" = false

[ "Amount of Trinket Slot Obtainable:" ]
  # Range: 0 ~ 99
  "How many trinket slots?" = 4

[ "Speed Force Particles" ]
  "Show particles?" = true

