
#General mod settings
[general]
	#Range: 1.0 ~ 30000.0
	tileEntityRenderRangeMax = 24.0
	#Range: 1.0 ~ 30000.0
	entityRenderRangeMax = 15000
	tileEntityRenderLimitModdedOnly = true
	entityRenderLimitModdedOnly = true

