
#Command Settings
[commands]

	[commands.general]
		#Command messages show to all players on server.
		msgAllPlayers = false
		#Sets all command to be this permission level.
		#Range: 0 ~ 4
		cmdPermissionsLevel = 2
		#Commands show a message in chat.
		msgShow = true

	#InventoryBomb Command Settings
	[commands.InventoryBomb]
		#Item that will replace all inventory slots with after items are dropped
		inventoryBombItem = "minecraft:dead_bush"

	#DisconnectPlayer Command Settings
	[commands.DisconnectPlayer]
		#Message to show when disconnected
		disconnectMsg = " and had a Dark PANIC moment and some how left the server."

	#PlayerNudger Command Settings
	[commands.PlayerNudger]

		[commands.PlayerNudger.North]
			#Chance for playernudger command to nudge North
			#Range: 0 ~ 100
			North_Chance = 4
			#Strength of playernudger command nudging North
			#Range: 0.0 ~ 10.0
			North_Strength = 0.7

		[commands.PlayerNudger.NorthEast]
			#Chance for playernudger command to nudge Northeast
			#Range: 0 ~ 100
			Northeast_Chance = 2
			#Strength of playernudger command nudging Northeast
			#Range: 0.0 ~ 10.0
			Northeast_Strength = 0.7

		[commands.PlayerNudger.East]
			#Chance for playernudger command to nudge East
			#Range: 0 ~ 100
			East_Chance = 4
			#Strength of playernudger command nudging East
			#Range: 0.0 ~ 10.0
			East_Strength = 0.7

		[commands.PlayerNudger.SouthEast]
			#Chance for playernudger command to nudge Southeast
			#Range: 0 ~ 100
			SouthEast_Chance = 2
			#Strength of playernudger command nudging Southeast
			#Range: 0.0 ~ 10.0
			SouthEast_Strength = 0.7

		[commands.PlayerNudger.South]
			#Chance for playernudger command to nudge South
			#Range: 0 ~ 100
			South_Chance = 4
			#Strength of playernudger command nudging South
			#Range: 0.0 ~ 10.0
			South_Strength = 0.7

		[commands.PlayerNudger.SouthWest]
			#Chance for playernudger command to nudge Southwest
			#Range: 0 ~ 100
			SouthWest_Chance = 2
			#Strength of playernudger command nudging Southwest
			#Range: 0.0 ~ 10.0
			SouthWest_Strength = 0.7

		[commands.PlayerNudger.West]
			#Chance for playernudger command to nudge West
			#Range: 0 ~ 100
			West_Chance = 4
			#Strength of playernudger command nudging West
			#Range: 0.0 ~ 10.0
			West_Strength = 0.7

		[commands.PlayerNudger.NorthWest]
			#Chance for playernudger command to nudge Northwest
			#Range: 0 ~ 100
			NorthWest_Chance = 2
			#Strength of playernudger command nudging Northwest
			#Range: 0.0 ~ 10.0
			NorthWest_Strength = 0.7

		[commands.PlayerNudger.Up]
			#Chance for playernudger command to nudge Up
			#Range: 0 ~ 100
			Up_Chance = 1
			#Strength of playernudger command nudging Up
			#Range: 0.0 ~ 10.0
			Up_Strength = 0.7

		[commands.PlayerNudger.Down]
			#Chance for playernudger command to nudge Down
			#Range: 0 ~ 100
			Down_Chance = 0
			#Strength of playernudger command nudging Down
			#Range: 0.0 ~ 10.0
			Down_Strength = 0.7

		[commands.PlayerNudger.PlayerFacingDirections]
			#Multiplier to increase the chance to nudge where the player is looking
			#Range: 0 ~ 100
			Forward_Multiplier = 1
			#Multiplier to increase the chance to nudge opposite where the player is looking
			#Range: 0 ~ 100
			Backward_Multiplier = 1
			#Multiplier to increase the chance to nudge the player to the left
			#Range: 0 ~ 100
			Left_Multiplier = 1
			#Multiplier to increase the chance to nudge the player to the right
			#Range: 0 ~ 100
			Right_Multiplier = 1

	#RandomTeleport Command Settings
	[commands.RandomTeleport]

		[commands.RandomTeleport."X Axis"]
			#Miniumum X offset from original X level. (i.e. 10 means when teleported will be at least 10 blocks along the X axis from original position)
			#Range: 0 ~ 100000
			randomTeleportXMin = 100
			#Maximum X offset from original X level. (i.e. 100 means when teleported will be less than 100 blocks away on the X axis from original position)
			#Range: 0 ~ 100000
			randomTeleportXMax = 500

		[commands.RandomTeleport."Y Axis"]
			#Miniumum Y offset from original Y level. (i.e. 10 means when teleported will be at least 10 blocks higher or lower than original position)
			#Range: 0 ~ 30000000
			randomTeleportYMin = 1
			#Maximum Y offset from original Y level. (i.e. 100 means when teleported will be less than 100 blocks higher or lower than original position)
			#Range: 0 ~ 30000000
			randomTeleportYMax = 10

		[commands.RandomTeleport."Z Axis"]
			#Miniumum Z offset from original X level. (i.e. 10 means when teleported will be at least 10 blocks along the Z axis from original position)
			#Range: 0 ~ 100000
			randomTeleportZMin = 100
			#Maximum Z offset from original X level. (i.e. 100 means when teleported will be less than 100 blocks away on the Z axis from original position)
			#Range: 0 ~ 100000
			randomTeleportZMax = 500

	#QuickHide Command Settings
	[commands.QuickHide]
		#List of random options that can be chosen when using quickhide command
		QuickHideList = ["minecraft:dead_bush,quick hide in these bushes!", "minecraft:wheat,quick hide in the wheat field!", "minecraft:feather,quick act like a chicken!", "minecraft:painting,quick blend into the wall!"]

	#SummonMount Command Settings
	[commands.SummonMount]
		#List of Classifications for SummonMount command to INCLUDE from possible entities. Use "ANY" for all.
		SummonMountClass = ["ambient", "creature", "water_creature", "water_ambient", "monster"]
		#List of entities for SummonMount command to EXCLUDE from possible entities
		SummonMount = ["adpother:gas", "adpother:purified_air", "alexsmobs:anaconda_part", "alexsmobs:bone_serpent_part", "alexsmobs:centipede_body", "alexsmobs:centipede_tail", "alexsmobs:pollen_ball", "alexsmobs:tossed_item", "alexsmobs:vine_lasso", "alexsmobs:void_portal", "alexsmobs:void_worm_part", "alexsmobs:void_worm_shot", "apotheosis:broadhead_arrow", "apotheosis:explosive_arrow", "apotheosis:mining_arrow", "apotheosis:obsidian_arrow", "camera:image_frame", "cofh_core:black_hole", "cofh_core:electric_arc", "cofh_core:electric_field", "cofh_core:knife", "core_creepers:ambush_creeper", "core_creepers:cluster_creeper", "core_creepers:dirt_creeper", "core_creepers:dirt_water_creeper", "core_creepers:stone_creeper", "core_creepers:stone_lava_creeper", "core_creepers:super_charged_creeper", "create:carriage_contraption", "create:contraption", "create:crafting_blueprint", "create:gantry_contraption", "create:potato_projectile", "create:seat", "create:stationary_contraption", "create:super_glue", "cyclic:boomerang_carry", "cyclic:boomerang_damage", "cyclic:boomerang_stun", "cyclic:conveyor_item", "cyclic:darkfire_bolt", "cyclic:dungeon", "cyclic:ender_fishing", "cyclic:eye", "cyclic:fire_bolt", "cyclic:laser_bolt", "cyclic:lightning_bolt", "cyclic:magic_missile", "cyclic:magic_net", "cyclic:snow_bolt", "cyclic:stone_bolt", "cyclic:torch_bolt", "delivery:drone", "dimpaintings:dimensional_painting", "dirt_flinger:thrown_dirt", "eyesinthedarkness:eyes", "farmersdelight:rotten_tomato", "gateways:gateway", "glow_sticks:glow_stick", "glowinc:glow_ball_entity", "graveyard:skeleton_creeper", "gravityforce:physics_block", "insanelib:area_effect_cloud_3d", "luggage:luggage", "minecraft:area_effect_cloud", "minecraft:armor_stand", "minecraft:arrow", "minecraft:command_block_minecart", "minecraft:creeper", "minecraft:dragon_fireball", "minecraft:egg", "minecraft:ender_dragon", "minecraft:ender_pearl", "minecraft:evoker_fangs", "minecraft:experience_bottle", "minecraft:experience_orb", "minecraft:eye_of_ender", "minecraft:falling_block", "minecraft:fireball", "minecraft:firework_rocket", "minecraft:fishing_bobber", "minecraft:glow_item_frame", "minecraft:item", "minecraft:item_frame", "minecraft:leash_knot", "minecraft:llama_spit", "minecraft:marker", "minecraft:painting", "minecraft:player", "minecraft:potion", "minecraft:shulker_bullet", "minecraft:small_fireball", "minecraft:snowball", "minecraft:spectral_arrow", "minecraft:trident", "minecraft:wither", "minecraft:wither_skull", "projecte:fire_projectile", "projecte:homing_arrow", "projecte:lava_projectile", "projecte:lens_projectile", "projecte:mob_randomizer", "projecte:nova_cataclysm_primed", "projecte:nova_catalyst_primed", "projecte:swrg_projectile", "projecte:water_projectile", "sophisticatedbackpacks:everlasting_backpack_item", "tconstruct:efln_ball", "tconstruct:fancy_item_frame", "tconstruct:flint_shuriken", "tconstruct:glow_ball", "tconstruct:indestructible_item", "tconstruct:quartz_shuriken", "thermal:basalz_projectile", "thermal:blitz_projectile", "thermal:blizz_projectile", "thermal:earth_grenade", "thermal:earth_tnt", "thermal:ender_grenade", "thermal:ender_tnt", "thermal:explosive_grenade", "thermal:fire_grenade", "thermal:fire_tnt", "thermal:glowstone_grenade", "thermal:glowstone_tnt", "thermal:ice_grenade", "thermal:ice_tnt", "thermal:lightning_grenade", "thermal:lightning_tnt", "thermal:nuke_grenade", "thermal:nuke_tnt", "thermal:phyto_grenade", "thermal:phyto_tnt", "thermal:redstone_grenade", "thermal:redstone_tnt", "thermal:slime_grenade", "thermal:slime_tnt", "tntslimes:tnt_slime", "graveyard:falling_corpse", "alexsmobs:cachalot_echo", "alexsmobs:centipede_head", "alexsmobs:cockroach_egg", "alexsmobs:crow", "alexsmobs:emu_egg", "alexsmobs:enderiophage_rocket", "alexsmobs:ice_shard", "alexsmobs:mimicube", "alexsmobs:mosquito_spit", "alexsmobs:sand_shot", "alexsmobs:shark_tooth_arrow", "alexsmobs:skelewag", "alexsmobs:squid_grapple", "alexsmobs:void_worm", "dabomb:bee_bomb", "dabomb:bomb", "dabomb:bomb_fish", "dabomb:bouncy_bomb", "dabomb:bouncy_dynamite", "dabomb:c4", "dabomb:dirt_bomb", "dabomb:dry_bomb", "dabomb:dynamite", "dabomb:ender_bomb", "dabomb:flower_bomb", "dabomb:lava_bomb", "dabomb:sticky_bomb", "dabomb:sticky_dynamite", "dabomb:water_bomb", "distantfriends:friend", "graveyard:falling_corpse", "graveyard:lich", "impostore:impost_ore", "minecraft:boat", "minecraft:chest_minecart", "minecraft:elder_guardian", "minecraft:end_crystal", "minecraft:furnace_minecart", "minecraft:giant", "minecraft:hopper_minecart", "minecraft:lightning_bolt", "minecraft:minecart", "minecraft:phantom", "minecraft:piglin_brute", "minecraft:ravager", "minecraft:spawner_minecart", "minecraft:tnt", "minecraft:tnt_minecart", "minecraft:vex", "minecraft:vindicator", "minecraft:zoglin", "mowziesmobs:axe_attack", "mowziesmobs:baby_foliaath", "mowziesmobs:barako", "mowziesmobs:barakoa_sunblocker", "mowziesmobs:barakoa_sunblocker_player", "mowziesmobs:barakoan_player", "mowziesmobs:block_swapper", "mowziesmobs:boulder_platform", "mowziesmobs:boulder_projectile", "mowziesmobs:camera_shake", "mowziesmobs:dart", "mowziesmobs:falling_block", "mowziesmobs:foliaath", "mowziesmobs:frostmaw", "mowziesmobs:frozen_controller", "mowziesmobs:ice_ball", "mowziesmobs:ice_breath", "mowziesmobs:naga", "mowziesmobs:pillar", "mowziesmobs:pillar_piece", "mowziesmobs:poison_ball", "mowziesmobs:solar_beam", "mowziesmobs:sunstrike", "mowziesmobs:super_nova", "tconstruct:crystalshot", "witherstormmod:block_cluster", "witherstormmod:command_block", "witherstormmod:flaming_wither_skull", "witherstormmod:formidibomb", "witherstormmod:wither_storm", "witherstormmod:wither_storm_head", "witherstormmod:wither_storm_segment", "witherstormmod:withered_symbiont", "witherstormmod:super_tnt", "alexsmobs:hemolymph", "alexsmobs:straddleboard", "alexsmobs:warped_mosco"]
		#Custom name for SummonMount entities.
		summonMountCustomName = true
		#Try to summon entity already tamed.
		summonMountTamed = true

	#SummonRider Command Settings
	[commands.SummonRider]
		#List of Classifications for SummonRide command to INCLUDE from possible entities. Use "ANY" for all.
		SummonRiderClass = ["ambient", "creature", "water_creature", "water_ambient"]

	#DisplayDeathBoard Command Settings
	[commands.DisplayDeathBoard]
		#List of strings to put at the end based on position. Ranks without a separate value will use whatever the last value is
		DisplayDeathBoard = [" rip"]

	#RandomGift Command Settings
	[commands.RandomGift]
		#List of items (resource location,amount,weighted chance) to be chosen for RandomGift command to choose from
		RandomGift = ["minecraft:diamond,1,1", "minecraft:feather,64,99"]

	#RandomTeleportDirection Command Settings
	[commands.RandomTeleportDirection]
		#Teleports user in a random direction with the given amount as distance from their original spot
		#Range: 0 ~ 100000
		RandomTeleportDirection = 500
		#Miniumum Y offset from original Y level. (i.e. 10 means when teleported will be at least 10 blocks higher or lower than original position
		#Range: 0 ~ 30000000
		randomTeleportdDirectionYMin = 0
		#Maximum Y offset from original Y level. (i.e. 100 means when teleported will be less than 100 blocks higher or lower than original position
		#Range: 0 ~ 30000000
		randomTeleportYDirectionMax = 320

	#RandomEnchanting Command Settings
	[commands.RandomEnchanting]
		#List of enchantment(s) for RandomEnchanting command to EXCLUDE from possible enchantments (i.e. minecraft:vanishing_curse)
		RandomEnchantingExclude = ["walljump:walljump"]
		#Force random enchantment on even if normally cannot go on item.
		randomEnchantForce = true

