# This is a list of entities that will not be rendered by TOP. This option also works if it is set client-side alone
renderBlacklist = ["minecraft:area_effect_cloud", "minecraft:arrow", "minecraft:boat", "minecraft:dragon_fireball", "minecraft:evoker_fangs", "minecraft:experience_orb", "minecraft:falling_block", "minecraft:firework_rocket", "minecraft:glow_item_frame", "minecraft:item", "minecraft:item_frame", "minecraft:fireball", "minecraft:leash_knot", "minecraft:lightning_bolt", "minecraft:llama_spit", "minecraft:minecart", "minecraft:chest_minecart", "minecraft:command_block_minecart", "minecraft:furnace_minecart", "minecraft:hopper_minecart", "minecraft:spawner_minecart", "minecraft:tnt_minecart", "minecraft:polar_bear", "minecraft:shulker_bullet", "minecraft:small_fireball", "minecraft:snowball", "minecraft:spectral_arrow", "minecraft:experience_bottle", "minecraft:potion", "minecraft:trident", "minecraft:wither_skull", "minecraft:player", "minecraft:fishing_bobber", "create:super_glue", "create:crafting_blueprint", "create:contraption", "create:stationary_contraption", "create:gantry_contraption", "create:carriage_contraption", "create:potato_projectile", "create:seat", "gateways:gateway", "apotheosis:obsidian_arrow", "apotheosis:broadhead_arrow", "apotheosis:explosive_arrow", "apotheosis:mining_arrow", "projecte:fire_projectile", "projecte:homing_arrow", "projecte:lava_projectile", "projecte:lens_projectile", "projecte:mob_randomizer", "projecte:nova_catalyst_primed", "projecte:nova_cataclysm_primed", "projecte:swrg_projectile", "projecte:water_projectile", "dabomb:bomb", "dabomb:bouncy_bomb", "dabomb:sticky_bomb", "dabomb:bomb_fish", "dabomb:dirt_bomb", "dabomb:dry_bomb", "dabomb:water_bomb", "dabomb:lava_bomb", "dabomb:bee_bomb", "dabomb:flower_bomb", "dabomb:ender_bomb", "dabomb:dynamite", "dabomb:sticky_dynamite", "dabomb:bouncy_dynamite", "dabomb:c4", "cofh_core:knife", "cofh_core:electric_arc", "cofh_core:electric_field", "thermal:basalz", "thermal:blizz", "thermal:blitz", "thermal:basalz_projectile", "thermal:blizz_projectile", "thermal:blitz_projectile", "thermal:explosive_grenade", "thermal:fire_grenade", "thermal:ice_grenade", "thermal:lightning_grenade", "thermal:earth_grenade", "thermal:ender_grenade", "thermal:glowstone_grenade", "thermal:redstone_grenade", "thermal:slime_grenade", "thermal:phyto_grenade", "thermal:nuke_grenade", "thermal:fire_tnt", "thermal:ice_tnt", "thermal:lightning_tnt", "thermal:earth_tnt", "thermal:ender_tnt", "thermal:glowstone_tnt", "thermal:redstone_tnt", "thermal:slime_tnt", "thermal:phyto_tnt", "thermal:nuke_tnt", "gravityforce:physics_block", "insanelib:area_effect_cloud_3d", "alexsmobs:shark_tooth_arrow", "alexsmobs:tossed_item", "alexsmobs:sand_shot", "alexsmobs:cachalot_echo", "alexsmobs:enderiophage_rocket", "alexsmobs:void_worm_shot", "sophisticatedbackpacks:everlasting_backpack_item", "dirt_flinger:thrown_dirt", "impostore:impost_ore", "farmersdelight:rotten_tomato", "born_in_chaos_v1:projectile_staffof_blindness", "born_in_chaos_v1:fallenchaosknight_n", "born_in_chaos_v1:projectile_staffof_magic_arrows", "eyesinthedarkness:eyes", "camera:image_frame", "cyclic:magic_net", "cyclic:torch_bolt", "cyclic:boomerang_stun", "cyclic:boomerang_carry", "cyclic:boomerang_damage", "cyclic:dungeon", "cyclic:eye", "cyclic:lightning_bolt", "cyclic:snow_bolt", "cyclic:fire_bolt", "cyclic:stone_bolt", "cyclic:laser_bolt", "cyclic:magic_missile", "cyclic:conveyor_item", "cyclic:darkfire_bolt", "cyclic:ender_fishing", "artifacts:mimic", "distantfriends:friend", "tconstruct:fancy_item_frame", "tconstruct:glow_ball", "tconstruct:efln_ball", "tconstruct:quartz_shuriken", "tconstruct:flint_shuriken", "tconstruct:indestructible_item", "luggage:luggage"]
# The amount of milliseconds to wait before updating probe information from the server
# Range: 10 ~ 100000
timeout = 300
# The amount of milliseconds to wait before showing a 'fetch from server' info on the client (if the server is slow to respond) (-1 to disable this feature)
# Range: -1 ~ 100000
waitingForServerTimeout = 3500
# The maximum packet size to send an itemstack from client to server. Reduce this if you have issues with network lag caused by TOP
# Range: -1 ~ 32768
maxPacketToServer = 20000
# Distance at which the probe works
# Range: 0.1 ~ 200.0
probeDistance = 6.0
# Show mod name (0 = not, 1 = always, 2 = sneak)
showModName = "NORMAL"
# Show harvest level (0 = not, 1 = always, 2 = sneak)
showHarvestLevel = "NORMAL"
# Show if the block can be harvested (0 = not, 1 = always, 2 = sneak)
showCanBeHarvested = "NORMAL"
# Show the growth level of crops (0 = not, 1 = always, 2 = sneak)
showCropPercentage = "NORMAL"
# Show chest contents (0 = not, 1 = always, 2 = sneak)
showChestContents = "EXTENDED"
# Show chest contents in detail (0 = not, 1 = always, 2 = sneak), used only if number of items is below 'showItemDetailThresshold'
showChestContentsDetailed = "EXTENDED"
# Show redstone (0 = not, 1 = always, 2 = sneak)
showRedstone = "NORMAL"
# Show mob health (0 = not, 1 = always, 2 = sneak)
showMobHealth = "NORMAL"
# Show time to adulthood for baby mobs (0 = not, 1 = always, 2 = sneak)
showMobGrowth = "NORMAL"
# Show mob potion effects (0 = not, 1 = always, 2 = sneak)
showMobPotionEffects = "EXTENDED"
# Show lever/comparator/repeater settings (0 = not, 1 = always, 2 = sneak)
showLeverSetting = "NORMAL"
# Show tank setting (0 = not, 1 = always, 2 = sneak)
showTankSetting = "EXTENDED"
# Show brewing stand setting (0 = not, 1 = always, 2 = sneak)
showBrewStandSetting = "NORMAL"
# Show mob spawner setting (0 = not, 1 = always, 2 = sneak)
showMobSpawnerSetting = "NORMAL"
# Show animal owner setting (0 = not, 1 = always, 2 = sneak)
showAnimalOwnerSetting = "EXTENDED"
# Show horse stats setting (0 = not, 1 = always, 2 = sneak)
showHorseStatSetting = "EXTENDED"
# Reveal monster eggs (0 = not, 1 = always, 2 = sneak)
showSilverfish = "NOT"
# The distance to the left side of the screen. Use -1 if you don't want to set this
# Range: -1 ~ 10000
boxLeftX = 5
# The distance to the right side of the screen. Use -1 if you don't want to set this
# Range: -1 ~ 10000
boxRightX = -1
# The distance to the top side of the screen. Use -1 if you don't want to set this
# Range: -1 ~ 10000
boxTopY = -1
# The distance to the bottom side of the screen. Use -1 if you don't want to set this
# Range: -1 ~ 10000
boxBottomY = -1
# Color of the border of the box (0 to disable)
boxBorderColor = "ffef892c"
# Color of the box (0 to disable)
boxFillColor = "55431a0f"
# Thickness of the border of the box (0 to disable)
# Range: 0 ~ 20
boxThickness = 2
# How much the border should be offset (i.e. to create an 'outer' border)
# Range: 0 ~ 20
boxOffset = 0
# If true show liquid information when the probe hits liquid first
showLiquids = true
# Toggle default probe visibility (client can override)
isVisible = true
# If true then the probe hotkey must be held down to show the tooltip
holdKeyToMakeVisible = false
# The scale of the tooltips, 1 is default, 2 is smaller
# Range: 0.4 ~ 5.0
tooltipScale = 1.0
# Color of the border of the chest contents box (0 to disable)
chestContentsBorderColor = "ff006699"
# 0 means don't show break progress, 1 is show as bar, 2 is show as text
# Range: 0 ~ 2
showBreakProgress = 1
# true means shows harvestability with vanilla style icons
harvestStyleVanilla = true

[ style ]
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Label = "gray"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Warning = "yellow"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Obsolete = "gray,strikethrough"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  High = "gold"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  InfoImportant = "blue"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Progress = "white"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Name = "white"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Info = "white"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Error = "red,bold"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  Ok = "green"
  # Text style. Use a comma delimited list with colors like: 'red', 'green', 'blue', ... or style codes like 'underline', 'bold', 'italic', 'strikethrough', ..."
  ModName = "gold,italic"

