
[ World ]

  [ World.Ores ]

    [ World.Ores.Silver ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Lead ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Nickel ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Sulfur ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Tin ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Niter ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores."Oil Sand" ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Cinnabar ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

    [ World.Ores.Apatite ]
      # Max number of veins per chunk; set to 0 to disable.
      # Range: 0 ~ 64
      "Vein Count" = 0
      # Max size of the vein.
      # Range: 1 ~ 64
      "Vein Size" = 1
      # Minimum Y spawn.
      # Range: -2032 ~ 2031
      "Min Y" = 10
      # Maximum Y spawn.
      # Range: -2032 ~ 2031
      "Max Y" = 120

