
#Client options
[client]
	#DEFAULT=true. Toggles the rendering of the debris cloud surrounding the Wither Storm. Reload Type: NONE
	renderDebrisCloud = true
	#DEFAULT=true. Toggles the rendering of debris rings that surround the Wither Storm (much more performant than the debris cloud). Reload Type: NONE
	renderDebrisRings = true
	#DEFAULT=false. Renders the debris in the debris cloud as 2D objects instead of 3D. Reload Type: NONE
	renderDebrisTwoDimensional = false
	#DEFAULT=true. Setting this value to false will disable the debris cloud when rendering the Wither Storm from large distances. Reload Type: NONE
	renderDistantDebris = true
	#DEFAULT=false. Specifies if the debris particles orbiting segments should be rendered. Reload Type: NONE
	renderSegmentDebris = false
	#DEFAULT=true. Specifies if debris should render as 2D objects during phase 6 and above. Reload Type: NONE
	lowerDebrisResWithPhase = true
	#DEFAULT=false. Specifies if the low res models should be used when being rendered via the distant renderer. Reload Type: NONE
	witherStormLOD = false
	#DEFAULT=false. Uses larger cubes to make up the the phase 4 and up models. May result in a performance increase. Reload Type: NONE
	lowResModels = false
	#DEFAULT=true. Toggles the rendering of the tractor beams. Reload Type: NONE
	renderTractorBeams = true
	#DEFAULT=true. Specifies if a pulsating effect, mimicking endermen pulling the Wither Storm apart, should be rendered once its evolution is complete. Reload Type: NONE
	renderPulse = true
	#DEFAULT=true. The distant renderer allows for the Wither Storm to be rendered from much greater distances than what vanilla allows. Disable if you're facing issues with it. Reload Type: NONE
	distantRenderer = true
	#DEFAULT=true. Toggles the rendering of Block Clusters. Reload Type: NONE
	blockClusterRendering = true
	#DEFAULT=true. Specifies if an overlay should be applied to entities that renders wither sickness. Reload Type: GAME
	witherSicknessLayer = true
	#DEFAULT=true. Toggle to enable/disable the chromatic aberration effect. Reload Type: NONE
	chromaticAberration = true
	#DEFAULT=true. Specifies whether or not a white overlay should cover the screen during certain events. Reload Type: NONE
	blindingEffects = true
	#DEFAULT=true. Specifies whether or not camera shake effects should be used. Reload Type: NONE
	cameraShakeEffects = true
	#DEFAULT=true. Specifies if fog should be applied to Wither Storms being rendered from a distance. Reload Type: NONE
	distantFog = true
	#DEFAULT=true. Specifies if block clusters should be able to have special colouring and alpha applied to them. NOTE: DISABLE IF FACING CRASHES WHEN USING SHADERS WITH OPTIFINE. Reload Type: NONE
	blockClusterColouring = true
	#DEFAULT=true. Turn off to disable the ear ringing effects used in the mod. Reload Type: NONE
	earRingingEffects = true
	#DEFAULT=true. Turn off to disable the overlay that appears when inside a tractor beam. Reload Type: NONE
	renderTractorBeamOverlay = true
	#DEFAULT=true. Specifies if sky ambience affects (sky darkening) should render when a Wither Storm is nearby. Reload Type: NONE
	renderSkyAmbienceEffects = true
	#DEFAULT=true. Specifies if particles inside the tractor beams of the Wither Storm should render. Reload Type: NONE
	tractorBeamParticles = true
	#DEFAULT=false. Toggles the Wither Storm boss theme. NONE: this theme is from MC:SM and is subject to copyright. Reload Type: NONE
	playerWitherStormTheme = false
	#DEFAULT=true. Toggles the Withered Symbiont theme, created for CWSM by Mar Mar. Reload Type: NONE
	playSymbiontTheme = true
	#DEFAULT=true. Specifies if a purple shine should render behind the Wither Storm at night. Reload Type: NONE
	renderShine = true
	#DEFAULT=true. Uses the sphere fog shape instead of a cylindrical one, to allow the fog on the Wither Storm to be applied correctly. Disable if facing potential incompatibility issues. Reload Type: NONE
	alternativeEntityFogShape = true
	#DEFAULT=128. The RGB color of the tractor beams. Reload Type: NONE
	#Range: 0 ~ 255
	tractorBeamColorRed = 128
	#DEFAULT=77. The RGB color of the tractor beams. Reload Type: NONE
	#Range: 0 ~ 255
	tractorBeamColorGreen = 77
	#DEFAULT=204. The RGB color of the tractor beams. Reload Type: NONE
	#Range: 0 ~ 255
	tractorBeamColorBlue = 204
	#DEFAULT=true. Toggles the OptiFine warning upon joining a world. Reload Type: NONE
	optifineWarning = true
	#DEFAULT=true. Toggles April Fools special effects. Reload Type: NONE
	aprilFools = true

	#Instancing
	[client.instancing]
		#DEFAULT=true. Specifies if CWSM should use more performant rendering when rendering Block Clusters and the Wither Storm's mass. NOTE: It is not recommended to disable this option unless necessary. Reload Type: NONE
		vertexBufferRendering = true

