
#General settings
[general]
	#Dictates whether or not the vanilla biome places are enabled
	enableBiomePlaces = false
	#Dictates whether or not the vanilla dimension places are enabled (excluding the Overworld)
	enableDimensionPlaces = false
	#Dictates whether or not the default y place for going below 0 is enabled
	enableYPlaces = false

