
#General mod settings
[general]
	#Only spawn a zombie player if the player died by a zombie directly
	requiresDeathByZombieToSpawnZombiePlayer = false
	#Finds visible chests near and randomly moves contents around, only zombie players spawned from actual players use this
	messUpChests = true
	#
	opensDoors = true
	#
	pickupLootWhenHostile = false
	#
	pickupLootWhenCalm = true
	#To help prevent endless multiplication of zombies if you die near your own spawn point
	#Range: > -2147483648
	distanceFromPlayerSpawnPointToPreventZombieSpawn = 16
	#Spawn zombie players naturally in the world, will spawn in every biome zombies do
	Spawning_spawnZombiePlayersNaturally = true
	#Only used it Spawning_spawnZombiePlayersNaturally is true. Weight of zombie players, higher = more likely to spawn, vanilla sets zombie as 100
	#Range: > -2147483648
	Spawning_weight = 40
	#Only used it Spawning_spawnZombiePlayersNaturally is true. Minecraft profile names to use when naturally spawning in zombie players
	Spawning_playerNamesToUse = "Darkosto"
	#Any player that joins your dedicated server will have their name added to the Spawning_playerNamesToUse list
	automaticallyAddJoinedPlayersToNamesList = false
	#Use at own risk, will not support
	enableAdvancedDeveloperConfigFiles = false
	#items that will calm the zombie and let you train them, #food is a special match that will allow anything that the player can eat since a generic food data tag doesnt seem to exist yet
	calmingItems = "#food, minecraft:porkchop, minecraft:mutton, minecraft:tropical_fish, minecraft:beef, minecraft:chicken, minecraft:rabbit, minecraft:bread"
	#Shows name when looked at while hostile
	showNameWhenHostile = true

