
# -----------------------------------------------------------------------------------------
# Average distance between spawn attempts for Repurposed Structures Outposts.
# Will replace Vanilla Outposts with RS's themed Outposts if both would've been in same biome.
# 1 for spawning in most chunks and 1001 for none.
# Note: Vanilla Outposts will spawn again if a RS Outpost's entry is set to 1001 for the biome.
[ Outposts ]
  # Range: 1 ~ 1001
  outpostBirchAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostJungleAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostGiantTreeTaigaAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostDesertAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostBadlandsAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostSnowyAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostIcyAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostOakAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostTaigaAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  netherBrickOutpostAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  warpedOutpostAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  crimsonOutpostAverageChunkDistance = 1001
  # Range: 1 ~ 1001
  outpostEndAverageChunkDistance = 1001

