
#-----------------------------------------------------------------------------------------
#Average distance between spawn attempts for Repurposed Structures Villages 
#1 for spawning in most chunks and 1001 for no spawn.
[Spawnrates]
	#Range: 1 ~ 1001
	badlandsVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	birchVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	darkForestVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	jungleVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	swampVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	mountainsVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	villageMushroomAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	giantTaigaVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	oakVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	crimsonVillageAverageChunkDistance = 1001
	#Range: 1 ~ 1001
	warpedVillageAverageChunkDistance = 1001

#-----------------------------------------------------------------------------------------
#Size of the village. This is how many pieces long a path can be from the start piece.
[Size]
	#Range: 1 ~ 30
	badlandsVillageSize = 10
	#Range: 1 ~ 30
	birchVillageSize = 6
	#Range: 1 ~ 30
	darkForestVillageSize = 6
	#Range: 1 ~ 30
	jungleVillageSize = 8
	#Range: 1 ~ 30
	swampVillageSize = 6
	#Range: 1 ~ 30
	mountainsVillageSize = 6
	#Range: 1 ~ 30
	mushroomVillageSize = 8
	#Range: 1 ~ 30
	giantTaigaVillageSize = 6
	#Range: 1 ~ 30
	oakVillageSize = 6
	#Range: 1 ~ 30
	crimsonVillageSize = 6
	#Range: 1 ~ 30
	warpedVillageSize = 6

