# Example of attaching config files to audio channel.
# Copy and replace the part in brackets with the desired audio channel.
# This mod does not create custom audio channels. Here are the acceptable channel names.
# master, music, record, weather, block, hostile, neutral, player, ambient, voice
# Note that you can nest config files in folders by specifying the folder before it like folder/filename.

[music]
	main = "music/main"
	transitions = "music/transitions"
	commands = "music/commands"
	toggles = "music/toggles"
	redirect = "music/redirect"
	paused_by_jukebox = "true"
	overrides_normal_music = "true"

[ambient]
	main = "ambient/main"
	transitions = "ambient/transitions"
	commands = "ambient/commands"
	toggles = "ambient/toggles"
	redirect = "ambient/redirect"
	paused_by_jukebox = "false"
	overrides_normal_music = "false"
